from enum import Enum


class State(str, Enum):

    NONE = "NONE"
    PHONE = "PHONE"
    CODE = "CODE"
    PASSWORD = "PASSWORD"
    SOURCE_CHANNEL = "SOURCE_CHANNEL"
    TARGET_CHANNEL = "TARGET_CHANNEL"
    GROUP = "GROUP"
    GROUP_MESSAGE = "GROUP_MESSAGE"
    GROUP_SCHEDULE = "GROUP_SCHEDULE"
    REMOVE_LAST_LINES = "REMOVE_LAST_LINES"
    APPEND_LAST_LINES = "APPEND_LAST_LINES"
    SUPPORT = "SUPPORT"
    CONNECT_ACCOUNT = "CONNECT_ACCOUNT"
